name: test workflow

on:
  push:
    branches:
      - 'working'

jobs:
  test_job:
    runs-on: windows-latest
    steps:
      - name: test
        shell: pwsh
        run: |
          $line = '-' * 80; $br = $line + "`n" + $line
          $br
          git config --global user.name "Lateralus138"
          git config --global user.email "faithnomoread@yahoo.com"
          git clone "${{ github.server_url }}/${{ github.repository }}.git"
          $br
          git rev-parse --abbrev-ref HEAD
          $br
          git checkout working
          git rev-parse --abbrev-ref HEAD
          $br
          git checkout master
          git rev-parse --abbrev-ref HEAD
          $br
