name: test workflow

on:
  push:
    branches:
      - 'working'

jobs:
  test_job:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        shell: pwsh
        run: |
          $line = '-' * 80; $br = $line + "`n" + $line
          $br
          git config --global user.name "Lateralus138"
          git config --global user.email "faithnomoread@yahoo.com"
          git checkout working
          [DateTime]::UtcNow.ToString('u').Replace('Z', ' UTC') | Out-File -FilePath ".merge_history"
          git add .
          git commit -m "Updated .merge_history."
          git push origin working
          git checkout master
          git merge working
          git add .
          git push origin master
          $br
