name: Main Build
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.sln'
      - '**.yml'
      - '**.ps1'
      - '**.txt'
jobs:
  test2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test2
        shell: pwsh
        run: |
          Get-ChildItem .\test2 -Recurse -File | Where-Object { $_.Length -gt 0 }
