name: test workflow

on:
  push:
    branches:
      - 'working'

jobs:
  test_job:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        shell: pwsh
        run: |
          $line = '-' * 80; $br = $line + "`n" + $line
          $br
          git config --global user.name "Lateralus138"
          git config --global user.email "faithnomoread@yahoo.com"
          git merge  --no-commit --no-ff working
          git add .
          git commit --ammend -m "Merge working into master"
          git push origin master --force    
          $br
